### ISSUE TITLE
16/11/17

### ISSUE THREAD

**Issue by billism** [billism/timeline#13]
## 今日待办
- [ ] 完成 #7 Matplotlib 写作的第一章节. 基本已经完成, 主要是补充一下.
- [ ] 完成 #7 Matplotlib 写作的第二章节, 主要是关于布局. 先写出大体的内容, 后期再补充修改.
- [ ] 看完 #8 Hands on ML 第三章. 先看一遍, 以后再做.
- [ ] #2 Python Net Prog 的前三章, 因为已经看过了, 这次应该看的比较快.
- [ ] #6 LYAH 前三章, 做简单的笔记 Dynalist. 即可.

**Comment by billism** [comment]
今天一直在折腾服务器, 没有完成以上任何一项!
